FROM ubuntu:20.04

LABEL version="4.0.0" description="Minha imagem" maintainer="Kleberson Brandao<kleberson.souza@aluno.faculdadeimpacta.com.br>"

RUN apt-get update && apt-get --no-install-recommends -y install htop && rm -rf /var/lib/apt/lists/*&&  cd / && mkdir KLEBERSON 


CMD /bin/bash
