apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstapp
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: web
        image: gcr.io/containers-327522/myfirstapp:2.0
        ports:
        - name: http
          containerPort: 80
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379